export const products = [
  {
    id: 1,
    categoris: { id: 1, name: 'Plants and Machinery' },
    name: 'Mens backpack',
    color: 'White and black',
    imageSrc: '/img/products/bag.jpg',
    imageAlt: 'bagpack',
    price: 34,
    stock: false,
  },
  {
    id: 2,
    categoris: { id: 2, name: 'Products' },
    name: 'Water Bottle',
    color: 'White and black',
    imageSrc: '/img/products/bottle.jpg',
    imageAlt: 'Bottle',
    price: 8,
    stock: true,
  },
  {
    id: 3,
    categoris: { id: 3, name: 'Industrial' },
    name: 'Sun Glasses',
    color: 'White and black',
    imageSrc: '/img/products/glasses.jpg',
    imageAlt: 'bottle',
    price: 89,
    stock: true,
  },
  {
    id: 4,
    categoris: { id: 4, name: 'Materials' },
    name: 'Shirts',
    color: 'White and black',
    imageSrc: '/img/products/shirt.jpg',
    imageAlt: 'shirt',
    price: 29,
    stock: true,
  },
];
