export const products = [
  {
    id: 1,
    categoris: { id: 1, name: 'Plants and Machinery' },
    name: 'Hitachi UH045(120) Excavator',
    description: 'Hitachi Good condition',
    imageSrc: '/img/products/plantsandmachinery/excavator.jpg',
    imageAlt: 'excavator',
    price: 2800000.0,
    stock: true,
  },
  {
    id: 2,
    categoris: { id: 1, name: 'Plants and Machinery' },
    name: '00 breaker',
    description: 'SHMI 600 brand new breakers for sale',
    imageSrc: '/img/products/plantsandmachinery/00breaker.jpg',
    imageAlt: 'breaker',
    price: 975000,
    stock: true,
  },
  {
    id: 3,
    categoris: { id: 1, name: 'Plants and Machinery' },
    name: ' Pair of Jack Stand stands Tuzzle 2 Ton HUGO',
    description: 'Brand new',
    imageSrc: '/img/products/plantsandmachinery/pairofjacks.jpg',
    imageAlt: 'jacks',
    price: 2900.0,
    stock: true,
  },
  {
    id: 4,
    categoris: { id: 1, name: 'Plants and Machinery' },
    name: 'Mens backpack',
    description: 'White and black',
    imageSrc: '/img/products/plantsandmachinery/excavator.jpg',
    imageAlt: 'bagpack',
    price: 34,
    stock: false,
  },
  {
    id: 5,
    categoris: { id: 1, name: 'Plants and Machinery' },
    name: 'Ton double lever block with 1.5 m chain Torin Big Red',
    description: 'Torin Big Red brand lever block.',
    imageSrc: '/img/products/plantsandmachinery/tom.jpg',
    imageAlt: 'tondouble',
    price: 17500.0,
    stock: true,
  },
  {
    id: 6,
    categoris: { id: 2, name: 'Products' },
    name: '0.5Hp 130 MEN Centrifugal water pump with Japanese Technology',
    description: 'Centrifugal water pump from MEN brand with Japanese Technology',
    imageSrc: '/img/products/products/motor.jpg',
    imageAlt: 'tondouble',
    price: 11500.0,
    stock: true,
  },
  {
    id: 7,
    categoris: { id: 2, name: 'Products' },
    name: '1 MW solar power permit for sale',
    description: '1 MW solar power permit for sale',
    imageSrc: '/img/products/products/solar.jpg',
    imageAlt: 'solar',
    price: 88000.0,
    stock: true,
  },
  {
    id: 8,
    categoris: { id: 2, name: 'Products' },
    name: '1 KW Solar Panel System (Unit 100-120 kWh)',
    description: '1 KW Solar Panel System',
    imageSrc: '/img/products/products/solar2.jpg',
    imageAlt: 'solar2',
    price: 95000.0,
    stock: true,
  },
  {
    id: 9,
    categoris: { id: 2, name: 'Products' },
    name: '0.8mm Copper plated MIG welding wire Reel 15kg Mild Steel 70S-6',
    description: '15 kg Mig welding wire cable reels.',
    imageSrc: '/img/products/products/copperplated.jpg',
    imageAlt: 'cable',
    price: 4750.0,
    stock: true,
  },
  {
    id: 10,
    categoris: { id: 2, name: 'Products' },
    name: 'Aluminium Pantry Cupboards',
    description: 'Modern Classic Kitchen Pantry Cupboards from Srilanka EVER TRUST Interior',
    imageSrc: '/img/products/products/aluminium.jpg',
    imageAlt: 'aliminu',
    price: 4750.0,
    stock: true,
  },
  {
    id: 11,
    categoris: { id: 3, name: 'Industrial' },
    name: 'MIG 500 3 Phase Industrial Welding Plant',
    description: 'MIG 500 3 Phase Industrial Welding Plant new One',
    imageSrc: '/img/products/industrial/gen.jpeg',
    imageAlt: 'phanseIndustrial',
    price: 97500.0,
    stock: true,
  },
  {
    id: 12,
    categoris: { id: 3, name: 'Industrial' },
    name: 'INDUSTRIAL High Pressure Cleaning Machine.',
    description: 'High Pressure Cleaning Machine.',
    imageSrc: '/img/products/industrial/c-machine.png',
    imageAlt: 'pressue',
    price: 150000.0,
    stock: true,
  },
  {
    id: 13,
    categoris: { id: 3, name: 'Industrial' },
    name: 'Compressor – EMAX Industrial PLUS Series 120 Gal.',
    description: 'Industrial PLUS Series 120 Gal.',
    imageSrc: '/img/products/industrial/compress.jpg',
    imageAlt: 'compress',
    price: 125000.0,
    stock: true,
  },
  {
    id: 14,
    categoris: { id: 3, name: 'Industrial' },
    name: 'Compressor – Industrial Air 9 Gal.',
    description: ' Industrial Air 9 Gal.',
    imageSrc: '/img/products/industrial/compress2.jpg',
    imageAlt: 'compress',
    price: 125000.0,
    stock: true,
  },
  {
    id: 15,
    categoris: { id: 4, name: 'Materials' },
    name: '1 1/2 metal',
    description: 'without transport , price can be negotiable depend on the quantity',
    imageSrc: '/img/products/material/chip.jpg',
    imageAlt: 'metal',
    price: 5000.0,
    stock: true,
  },
  {
    id: 16,
    categoris: { id: 4, name: 'Materials' },
    name: '19mm Aggregates',
    description: 'best quality',
    imageSrc: '/img/products/material/aggre.jpg',
    imageAlt: 'agg',
    price: 7000.0,
    stock: true,
  },
  {
    id: 16,
    categoris: { id: 4, name: 'Materials' },
    name: '2*2 Teak Wood',
    description: 'Excellent finish',
    imageSrc: '/img/products/material/treak.jpg',
    imageAlt: 'agg',
    price: 7000.0,
    stock: true,
  },
  {
    id: 17,
    categoris: { id: 4, name: 'Materials' },
    name: '3/4 metal ',
    description: 'Deliver around Colombo',
    imageSrc: '/img/products/material/metal.jpg',
    imageAlt: 'agg',
    price: 7000.0,
    stock: true,
  },
];
